# Generated by Django 3.2.4 on 2021-10-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akta',
            old_name='berat_badan',
            new_name='bb',
        ),
        migrations.RenameField(
            model_name='akta',
            old_name='tinggi_badan',
            new_name='tb',
        ),
    ]
