# Generated by Django 3.2.4 on 2021-10-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akta',
            name='berat',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='tinggi',
            field=models.BigIntegerField(null=True),
        ),
    ]
