# Generated by Django 3.2.4 on 2021-10-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='nik_anak',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nomor_kk',
            field=models.BooleanField(),
        ),
    ]
