# Generated by Django 3.2.4 on 2021-10-31 10:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0002_auto_20211031_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='agama',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hinhu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='akta_nikah',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='anak_ke',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='hubungan_keluarga',
            field=models.CharField(choices=[('Ayah', 'Ayah'), ('Ibu', 'Ibu'), ('Lainnya', 'Lainnya')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='jam',
            field=models.TimeField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='jenis_kelahiran',
            field=models.CharField(choices=[('Tunggal', 'Tunggal'), ('Kembar Dua', 'Kembar Dua'), ('Kembar Tiga', 'Kembar Tiga'), ('Kembar Empat', 'Kembar Empat'), ('Kembar Banyak/Lainnya', 'Kembar Banyak/Lainnya')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki - Laki', 'Laki - Laki'), ('Perempuan', 'Perempuan')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='kk',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='ktp_ayah',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='ktp_ibu',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='ktp_saksi',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nama_anak',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nama_ayah',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nama_ibu',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nama_pelapor',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nama_saksi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nik_anak',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nik_ayah',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nik_ibu',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nik_kepala_keluarga',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nik_kepala_keluarga_pelapor',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nik_pelapor',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nik_saksi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='no_kk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='no_kk_pelapor',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='nomor_kk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='penolong_kelahiran',
            field=models.CharField(choices=[('Dokter', 'Dokter'), ('Bidan/Perawat', 'Bidan/Perawat'), ('Lainnya', 'Lainnya')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='rumah_sakit',
            field=models.CharField(choices=[('Rumah Sakit/Bersalin', 'Rumah Sakit/Bersalin'), ('Puskesmas', 'Puskesmas'), ('Polindes', 'Polindes'), ('Rumah', 'Rumah'), ('Lainnya', 'Lainnya')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='surat_kelahiran',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='tempat_lahir',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='tgl_lahir',
            field=models.DateField(max_length=250, null=True),
        ),
    ]
