# Generated by Django 3.2.4 on 2021-10-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0004_auto_20211026_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akta',
            name='surat_bukti_kelahiran',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='surat_pengantar_kelahiran',
        ),
        migrations.AddField(
            model_name='akta',
            name='agama',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hinhu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='anak_ke',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='berat_badan',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='jam',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='rumah_sakit',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='tinggi_badan',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
