# Generated by Django 3.2.4 on 2021-10-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0008_alter_akta_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akta',
            name='slug',
        ),
    ]
