# Generated by Django 3.2.4 on 2021-10-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0010_auto_20211030_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
