# Generated by Django 3.2.4 on 2021-10-30 07:31

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akta', '0012_alter_akta_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='akta',
            name='hubungan_keluarga',
            field=models.CharField(choices=[('Ayah', 'Ayah'), ('Ibu', 'Ibu'), ('Lainnya', 'Lainnya')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='jenis_kelahiran',
            field=models.CharField(choices=[('Tunggal', 'Tunggal'), ('Kembar Dua', 'Kembar Dua'), ('Kembar Tiga', 'Kembar Tiga'), ('Kembar Empat', 'Kembar Empat'), ('Kembar Banyak/Lainnya', 'Kembar Banyak/Lainnya')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='nama_pelapor',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='nik_kepala_keluarga',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='nik_kepala_keluarga_pelapor',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='nik_pelapor',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='no_kk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='no_kk_pelapor',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='penolong_kelahiran',
            field=models.CharField(choices=[('Dokter', 'Dokter'), ('Bidan/Perawat', 'Bidan/Perawat'), ('Lainnya', 'Lainnya')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='status',
            field=models.CharField(choices=[('data ditunggu', 'data ditunggu'), ('data disetujui', 'data disetujui'), ('data ditolak', 'data ditolak')], default='data ditunggu', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='surat_kelahiran',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='anak_ke',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki - Laki', 'Laki - Laki'), ('Perempuan', 'Perempuan')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='rumah_sakit',
            field=models.CharField(choices=[('Rumah Sakit/Bersalin', 'Rumah Sakit/Bersalin'), ('Puskesmas', 'Puskesmas'), ('Polindes', 'Polindes'), ('Rumah', 'Rumah'), ('Lainnya', 'Lainnya')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='tinggi_badan',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
