# Generated by Django 3.2.4 on 2021-10-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0013_auto_20211030_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='berat_badan',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='tinggi_badan',
            field=models.BooleanField(null=True),
        ),
    ]
