# Generated by Django 3.2.4 on 2021-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0015_auto_20211031_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='status',
            field=models.CharField(blank=True, choices=[('data ditunggu', 'data ditunggu'), ('data disetujui', 'data disetujui'), ('data ditolak', 'data ditolak')], default='data ditunggu', max_length=250, null=True),
        ),
    ]
