# Generated by Django 3.2.4 on 2021-10-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0016_alter_akta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akta',
            name='akta_nikah',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='kk',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='ktp_ayah',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='ktp_ibu',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='ktp_saksi',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='surat_kelahiran',
        ),
    ]
