# Generated by Django 3.2.4 on 2021-10-30 17:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0019_auto_20211031_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='akta_kawin_ortu',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='kk_ortu',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='ktp_ayah',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='ktp_ibu',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='ktp_saksi',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='surat_kelahiran',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
