# Generated by Django 3.2.4 on 2021-10-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0021_auto_20211031_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='berat_badan',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='tinggi_badan',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
