# Generated by Django 3.2.4 on 2021-10-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akta', '0022_auto_20211031_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='berat_badan',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='jam',
            field=models.TimeField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='tgl_lahir',
            field=models.DateField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='akta',
            name='tinggi_badan',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
